[2][nguyenduyan1231] 로그인 시작
[2][nguyenduyan1231] 로그인 종료
[2][nguyenduyan1231] 로그인 검증 시작
[2][nguyenduyan1231] 동의여부 체크 시작
[2][nguyenduyan1231] 동의여부 체크 종료 : 동의 필요하지 않음
[2][nguyenduyan1231] 로그인 검증 종료
[2][nguyenduyan1231] 로그인 성공여부 True - True
[2][nguyenduyan1231] 남은 수량 : 1
[2][nguyenduyan1231] 동의여부 체크 시작
[2][nguyenduyan1231] 동의여부 체크 종료 : 동의 필요하지 않음
[2][nguyenduyan1231] 팔로우 시작
[2][nguyenduyan1231] Traceback (most recent call last):
  File "/instahelp_web/docker_follow/follow_main.py", line 239, in process
    btn_elements = common.find_elements("CSS_SELECTOR", "button._acan", driver, wait)
  File "/instahelp_web/common/fun.py", line 411, in find_elements
    return wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, selector_name)))
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/instahelp_web/docker_follow/follow_main.py", line 229, in fetch_order
    result, message = process()
  File "/instahelp_web/docker_follow/follow_main.py", line 274, in process
    raise Exception(ex)
Exception: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/instahelp_web/docker_follow/follow_main.py", line 196, in dashboard
    result, message = fetch_order()
  File "/instahelp_web/docker_follow/follow_main.py", line 232, in fetch_order
    raise Exception(ex)
Exception: Message: 


[2][nguyenduyan1231] Task[0,1,태스크 실패]
[2][nguyenduyan1231] 마지막 메모리 사용량: 52.82 MB
