[6][olsd8smnnm] 로그인 시작
[6][olsd8smnnm] 로그인 종료
[6][olsd8smnnm] 로그인 검증 시작
[6][olsd8smnnm] 동의여부 체크 시작
[6][olsd8smnnm] Traceback (most recent call last):
  File "/instahelp_web/common/fun.py", line 894, in login
    if agree_check(account_id, tab_index, driver, wait):
  File "/instahelp_web/common/fun.py", line 803, in agree_check
    if agree.text == 'Instagram 앱을 사용하려면 다음 항목에 동의해야 합니다':
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 90, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome-headless-shell=126.0.6478.61); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x55de09e726aa <unknown>
#1 0x55de09b550dc <unknown>
#2 0x55de09b5a7e9 <unknown>
#3 0x55de09b5c595 <unknown>
#4 0x55de09b5c61c <unknown>
#5 0x55de09b9bae2 <unknown>
#6 0x55de09bc4872 <unknown>
#7 0x55de09b95d89 <unknown>
#8 0x55de09bc4a3e <unknown>
#9 0x55de09be35c3 <unknown>
#10 0x55de09bc4613 <unknown>
#11 0x55de09b944f7 <unknown>
#12 0x55de09b94e4e <unknown>
#13 0x55de09e3887b <unknown>
#14 0x55de09e3c921 <unknown>
#15 0x55de09e2436e <unknown>
#16 0x55de09e3d482 <unknown>
#17 0x55de09e08ccf <unknown>
#18 0x55de09e620a8 <unknown>
#19 0x55de09e62280 <unknown>
#20 0x55de09e717dc <unknown>
#21 0x7fc7bdf4f134 <unknown>


[6][olsd8smnnm] Task[0,1,로그인 실패]
[6][olsd8smnnm] 마지막 메모리 사용량: 13.09 MB
